// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isvmxcwucunissivvmdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzdm14Y3d1Y3VuaXNzaXZ2bWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4MTU2OTIsImV4cCI6MjA5ODM5MTY5Mn0.q9gHlJ47cpnK6zXwA7MZgEQYCl6TzbZ66BA8YfYHBuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});